.travis.yml

fix #38. This config file tells Travis to download the app dependencies and compile the app.

add TravisCI config file

---

grails-app/conf/Config.groovy

The issue was that intro.js and outro.js was trying to get minified, but they were not compatible. Since the application.js is pulling from jquery/dist the src folder and files inside were not getting used. In this case I just excluded the src files for jquery all together so they aren't included with the war build.
This fix does end up creating a empty src folder with empty folders inside in the built war. It does not however have any of the src javascript files which were causing the issue.
I believe it would also be possible to set minifyJs off for jquery, but this solution ensures that the jquery/dist files are getting minified.

fixes #31 . Excludes jquery/src from the asset compile

---

README.md

adds a link to the messageboard for streama on projecttalk.io.
not everyone is online at the same time, so this could be useful in addition to gitter.

add projecttalk link

---

grails-app/conf/DataSource.groovy

The docker environment was actually embedded within the production environment meaning it wasn't possible to set with `-Dgrails.env=docker`.

Correct indentation on groovy conf

---

grails-app/conf/Config.groovy
grails-app/services/streama/DefaultDataService.groovy

I changed the app context to root (e.g. `localhost:8080/` instead of `localhost:8080/streama`). I'm not sure why the app context wasn't switch to root before, but I figured the easiest way to start a discussion was to submit a pull request.

App Context

---

grails-app/assets/javascripts/directives/streama-video-player-directive.js
grails-app/assets/javascripts/streama-app/templates/streama-video-player.tpl.htm

Shortcut keys:
-Arrow keys up or down: volume.
-Arrow keys left or right: video time skip (20 seconds).
-Hold ctrl + press arrow keys to left or right: skip further (60 seconds).
-Alt + enter: toggle full screen.
-Backspace or delete: close video.
-S: toggle subtitles.
-M: toggle mute.
Miscellaneous:
-The fullscreen mode ends when you shut down the video player.
-Video's current time and duration are shown in upper right corner of the screen when the skip shortcut keys are used.
-The shortcut keys are disabled after the user closes the video player.
-Tested with Chrome and Firefox.
Issues:
-The player's current time updates slowly after skips are used.
Possible future improvements:
-The user can change skipping intervals from settings?

Video player keyboard shortcuts

---

grails-app/assets/javascripts/streama/controllers/admin-show-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/templates/admin-show.tpl.htm
grails-app/controllers/streama/TheMovieDbController.groovy

Fetch more than one season at once

---

grails-app/assets/javascripts/streama/controllers/admin-movies-ctrl.js
grails-app/assets/javascripts/streama/controllers/admin-show-ctrl.js
grails-app/assets/javascripts/streama/controllers/admin-shows-ctrl.js
grails-app/assets/javascripts/streama/controllers/dash-ctrl.js
grails-app/assets/javascripts/streama/controllers/modal-movie-ctrl.js
grails-app/assets/javascripts/streama/controllers/modal-tvshow-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/templates/admin-movies.tpl.htm
grails-app/assets/javascripts/streama/templates/admin-show.tpl.htm
grails-app/assets/javascripts/streama/templates/admin-shows.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--movie.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--tvShow.tpl.htm
grails-app/controllers/streama/TheMovieDbController.groovy
grails-app/init/BootStrap.groovy
grails-app/services/streama/MigrationService.groovy

Allowed for moviedb to not be used if the key is not present

Removed the dependency on TheMovieDb and made it optional

---

grails-app/assets/stylesheets/_player.scss
grails-app/assets/stylesheets/style.css

The loading spinner in the player is currently centered to its left border. By moving it it's width/2 (48px) left it will be centered correctly.

move loading spinner to the screen center

---

grails-app/assets/javascripts/streama/translations/EN_us.js

PROFIlE.SAVE_PASS was missing in the english translation. Is there any reason for the lowercase L in profile?

add missing PROFIlE.SAVE_PASS in english translation

---

grails-app/assets/javascripts/streama/directives/streama-video-player-directive.js

Using the "f" key is in parity with Netflix, Amazon Prime Video, and Hulu. I didn't know about "alt+enter" because I have that bound to something else in Compiz :)
This is just a minor usability request. No code changes, other than which bindkey to use. 
I also checked the other bindkeys, and "f" is not among them. There shouldn't be any collisions.

Changed bindkey for fullscreen FROM "alt+enter" TO "f"

---

grails-app/assets/javascripts/streama/controllers/player-ctrl.js
grails-app/assets/javascripts/streama/controllers/settings-settings-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/services/file-service.js
grails-app/assets/javascripts/streama/services/player-service.js
grails-app/assets/javascripts/streama/templates/settings-settings.tpl.htm
grails-app/controllers/streama/FileController.groovy
grails-app/services/streama/UploadService.groovy
grails-app/taglib/streama/AssetSettingTagLib.groovy
grails-app/views/index.gsp
grails-app/views/templates/_header.gsp
grails-app/views/templates/_header_anonymous.gsp
grails-app/views/templates/_header_simple.gsp

This removes the requirement to have the correct base URL set for playback of videos and other files. **The base URL is still used for invite links.**
For settings that are saved as a string to reference a file, they are now saved as `upload:$fileID` this is then translated to the correct URL on request. 
This also adds a setting `streama.servePrefix` that will prefix the `file/serve` path with a custom value. This is to assist with configurations where streama is not run on the root of the domain.
Fixes #334.

Base path removal

---

grails-app/assets/javascripts/streama/services/file-service.js
grails-app/assets/javascripts/streama/streama.run.js
grails-app/assets/javascripts/streama/templates/settings-settings.tpl.htm
grails-app/views/templates/_header.gsp
grails-app/views/templates/_header_anonymous.gsp

#511 introduced an issue where the assets (custom logo mainly) were not loading until you visited the settings page.

Fix issue where asset settings weren't loading on non-settings pages

---

grails-app/views/templates/_header.gsp
grails-app/views/templates/_header_anonymous.gsp
grails-app/views/templates/_header_simple.gsp

+ Fixes issue where sometimes the version number in the header would not show.
+ Moves version number to the right of the logo, moving to right prevents the header from changing height and looking bad.
+ Removes the version number from header_simple, just to keep the header for invite emails, etc. more *simple*.

Header version fix

---

grails-app/services/streama/SettingsService.groovy

Local and second directories only check for read perms.
Fixes #444

Make local and second directories only need read permissions

---

grails-app/assets/javascripts/streama/controllers/createFromFileCtrl.modal.js
grails-app/assets/javascripts/streama/templates/modal--create-from-file-recursive-item.tpl.htm
grails-app/assets/stylesheets/_admin.scss
grails-app/services/streama/BulkCreateService.groovy
grails-app/services/streama/TheMovieDbService.groovy

This PR is a potential fix for #480 #498 and #597. 
Now the application will cache some API calls that happen over and over (like the tv-show for a bunch of episodes) as well as first looking for existing DB records, which will hopefully resolve the most common LIMIT issue.

implement bulk api caching

---

grails-app/assets/javascripts/streama/directives/streama-video-player-directive.js

Add active flag judgment processing to mouse-wheel event handler method. This flag is set to false when the mouse cursor is on the episode list and to be true when leaving.
It seems that the indent setting of editorconfig and the indent of this file do not become consistent.

Disable volume control using mouse wheel on episode list (fix #315)

---

grails-app/assets/javascripts/streama/directives/streama-video-player-directive.js

For the initialization value, use the volume value stored in Local strage.
With this fix we are changing the argument of `setVolume` from a `slider` object to a number.

Add processing to initialize the volume during video playback

---

grails-app/controllers/streama/UserController.groovy

fixed the bug #729
the issuse is UserRole.removeAll does not apply to database immediately, So the UserRole constraints always stop apply new roles to user.
alternative solution:
-remove UserRole constraints

fixed "removes all roles" #729

---

grails-app/assets/javascripts/streama/templates/settings-settings.tpl.htm

I also found empty logo and favicon will breaks Streama as well.
fixed this bug using Angularjs validation . #747

Fixed Empty BG/logo/favicon breaks streama(fixed #747)

---

grails-app/conf/application.yml
grails-app/services/streama/BulkCreateService.groovy

Change the default movie regex to use negative check `[^\(\[]*` instead of `.*` for group Names. This prevents regex from going over the actual year and hitting something like 1080.
Example movie name:
`1. Die Hard (1988) BDRip 1080p H.265 [2xUKR_ENG].mkv`
I would prefer having regexes encapsulated into a separate class so they could be tested with a set of possible cases to make sure that any changes to regexes don't break anything. Thinking about including into this PR.

[WIP] Better regex for movie match

---

grails-app/services/streama/UploadService.groovy

Closed the upload file InputStream after uploading a TV show episode through the "Manage Files" button of an episode.
Launching the jar, after uploading multiple big files (TV show episodes) through the "Manage Files" button on the web interface, I was getting "java.io.IOException: No space left on device" on the console, and my 100% full /tmp partition would only free up the used disk space after killing the streama process. This was both in Ubuntu 18.04 LTS and Arch Linux VMs. Streama version v1.7.3.
Closing the uploaded file InputStream in UploadService.upload(request, params) method after it is no longer needed seems to correctly free up the disk space without having to run out, and having to kill and restart the application every time. Though I used v1.7.3, the InputStream still …

Bugfix - Properly closed manually-uploaded episode file InputStream

---

grails-app/conf/application.groovy

When logged in as a normal user, marking a video as unviewed would result in a "You don't have permission" error, while it was working fine for an admin user. This enables the "Mark as unviewed" feature for non-admin users as well.
(see https://github.com/streamaserver/streama/issues/1040#issuecomment-781658966)

Allow normal user to mark video unwatched

---

grails-app/assets/javascripts/streama/controllers/createFromFileCtrl.modal.js

This is aiming to fix issue #691 
Currently "Bulk-Create from file(s)" only selects files directly inside the selected directory, but not in subdirectories.
Here, when selecting a directory in "Bulk-Create from file(s)", all files directly in this main path will be selected and additionally all further files in first level subdirectories. These can then be parsed from imdb, without having to select files individually from all subdirectories.
As an example, assume the TV_Shows directory is mounted and has an example "Show_1" as below.
**/mnt/TV_Shows/**
...
**Show_1**
----_Season_1_
-------S01E01.mp4
-------S01E02.mp4
----_Season_2_
-------S02E01.mp4
-------S02E02.mp4
----Special_episode.mkv
...
By selecting directory Show_1, all episodes in the Season_1_and Season_2 directories are also …

Recursively add files in Bulk-Create

---

grails-app/assets/javascripts/streama/directives/streama-video-player-directive.js

Approach to fix issue #1055 
Instead of a fixed 30 s timeout from the end of videos before an "Up Next" popup shows, this will adjust the time gradually.
I used a 5 second timeout for a 2 minute video as a guideline, I believe this is reasonable for a short video. This ratio is then used between a minimum timeout of 3 seconds and a maximum of 30 seconds (`END_OF_VIDEO`).

Adjust Up Next timer on videos as function of duration

---

docker/docker-compose.yml

When I setup with docker I got error:
```sh
❯ docker-compose pull
Pulling mysql         ... pulling from library/mysql
Pulling streama       ... done
Pulling proxy-reverse ... done
ERROR: for mysql  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```
And I fixed

[Docker] Mysql build error for Apple M1

---

grails-app/controllers/streama/WatchlistEntryController.groovy
grails-app/services/streama/marshallers/MarshallerService.groovy

TV shows currently have a error adding to watchlist, due to the fact that they don't have a `video` property and specific properties inside the `video` object are extracted during this addition. 
I changed this so that it it simply assigns `response["tvShow"]` to the `tvShow` object and the `response["video"]` to the `video` objects. This way one of them can be `null` (as will always happen) and it will be added without errors to the list.
The second problem is that TV shows aren't even shown in the watchlist, because, again, their Entry don't have a `video` property and during `list` it was filtered by `video!=null`, which fails. 
I changed it so that it checks for `video!=null || tvShow!=null`. This way it prevents completely `null` entries and it works for both shows and movies.

Fixing error adding tv shows to watchlist
