streamaserver/streama

README.md

I had to guess a few combinations and look at the screenshots for the first time.
This should help people get up and running more quickly.
Cheers,
Christian

Added initial login details to readme

---

grails-app/assets/javascripts/controllers/player-ctrl.js

Fixed a typo in the error I keep seeing. =/

Attacking File Typo

---

.travis.yml

Since #44 brings a runnable test suite to the project, let TravisCI run them

[travis] make travis run the test suite

---

grails-app/i18n/messages_nb.properties

Small typo

---

grails-app/assets/javascripts/directives/streama-video-player-directive.js
grails-app/assets/javascripts/directives/video-time-format-directive.js
grails-app/assets/javascripts/services/player-service.js
grails-app/assets/javascripts/streama-app/templates/modal--video.tpl.htm
grails-app/domain/streama/Video.groovy
grails-app/services/streama/MarshallerService.groovy

Solved the issues on the latest pull request.

intro-skip retry

---

grails-app/assets/javascripts/controllers/modal-file-ctrl.js
grails-app/assets/javascripts/services/player-service.js
grails-app/assets/javascripts/streama-app/templates/admin-settings.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-show.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-users.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--genericVideo.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--movie.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--tvShow.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--user.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--video.tpl.htm
grails-app/assets/javascripts/streama-app/templates/profile.tpl.htm
grails-app/views/layouts/main.gsp
grails-app/views/login/auth.gsp

- E-mail changed to Username most everywhere.
- API ID -term changed to "Movie DB ID" most everywhere
- Codec/video playback error message now mentions to check the base URL if the video won't play (kind of a band-aid fix until the system can identify the problem more specifically)
- Cancel button colors unified to red
- Save settings -button placement unified with other main buttons on the other screens
- Save profile -button placement unified with other main buttons on the other screens
- Uploading a video/subtitle file gives a green 'Success' popup
- A couple of other small cosmetic changes
Notes:
- Not sure how relevant it is considering the changes, but everything was tested on Firefox
- There are a couple of files with back and forth -changes with no actual final change to Streama; …

Some cosmetic changes and a few others based on usability analysis 

---

grails-app/assets/javascripts/controllers/admin-fileManager-ctrl.js
grails-app/assets/javascripts/controllers/admin-movie-ctrl.js
grails-app/assets/javascripts/controllers/admin-notifications-ctrl.js
grails-app/assets/javascripts/controllers/admin-settings-ctrl.js
grails-app/assets/javascripts/controllers/admin-show-ctrl.js
grails-app/assets/javascripts/controllers/admin-users-ctrl.js
grails-app/assets/javascripts/controllers/admin-video-ctrl.js
grails-app/assets/javascripts/controllers/dash-ctrl.js
grails-app/assets/javascripts/controllers/modal-file-browser-ctrl.js
grails-app/assets/javascripts/controllers/modal-file-ctrl.js
grails-app/assets/javascripts/controllers/modal-generic-video-ctrl.js
grails-app/assets/javascripts/controllers/modal-movie-ctrl.js
grails-app/assets/javascripts/controllers/modal-tvshow-ctrl.js
grails-app/assets/javascripts/controllers/modal-video-ctrl.js
grails-app/assets/javascripts/services/player-service.js
grails-app/assets/javascripts/services/upload-service.js
grails-app/assets/javascripts/streama-app/templates/admin-fileManager.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-movie.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-movies.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-notifications.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-settings.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-show.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-shows.tpl.htm
grails-app/assets/javascripts/streama-app/templates/admin-video.tpl.htm
grails-app/assets/javascripts/streama-app/templates/dash.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--manage-files.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--movie.tpl.htm
grails-app/assets/javascripts/streama-app/templates/modal--tvShow.tpl.htm
grails-app/views/login/auth.gsp

-Added a reset button for the Base URL in settings menu
-Login screen now suggests using admin on username and password fields for a first time user.
-When adding a new TV Show, "Add Via API" is renamed to "Add automatically" and "Search for TV Show..." is renamed to "Search from TheMovieDb..." for both TV Shows and Movies.
-API ID, rating, rating count and genre are hidden when adding a TV Show or a Movie manually.
-File upload popup title renamed to "Video and subtitles for" to make it more obvious that both video and subtitle files can be uploaded there.
-Added a hovertext for the trashcan icon.
-Fixed Dashboard element alignment for different screen sizes.
-Renamed "Edit video/movie/show" to "Edit info".
-Rating, Rating count and Rating scale are hidden when there's no rating.
-"No …

Changes based on usability analysis

---

NL_nl.js
streama.translations.js

I translated the front end parts of streama to dutch.

Dutch Translation

---

grails-app/controllers/streama/TvShowController.groovy

I made several small and separate commits because the issues they related to were more or less distinct.
If someone finds this information useful 😁 
The code was tested on
_OS X 10.11.5
java version "1.8.0_92"
| Grails Version: 3.1.6
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_92
MySQL 5.7.12_

This fixes some issues with creating and deleting TV Shows

---

grails-app/controllers/streama/InviteController.groovy

Fixes dularion/streama#195

---

grails-app/views/episode/show.gson

Typecast Object to Episode before retrieving class property
thanks @	gkiko

Fixes #213

---

grails-app/assets/javascripts/translations/EN_us.js
grails-app/assets/javascripts/translations/ES_es.js
grails-app/assets/javascripts/translations/streama.translations.js
streama.translations.js

Here goes the Spanish Translation. I hope I did well enough with this PR!

Added Spanish translation

---

grails-app/assets/javascripts/streama/controllers/modal-user-ctrl.js
grails-app/assets/javascripts/streama/controllers/settings-users-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/services/modal-service.js
grails-app/assets/javascripts/streama/templates/modal--create-user.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--edit-user.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--invite-user.tpl.htm
grails-app/assets/javascripts/streama/templates/settings-users.tpl.htm
grails-app/controllers/streama/UserController.groovy

Adds the ability to register new users without the need send them an invite.
This should resolve #188

Added User registration without email

---

README.md
grails-app/assets/javascripts/translations/EN_us.js
grails-app/assets/javascripts/translations/ES_es.js
grails-app/assets/javascripts/translations/ko_KR.js
grails-app/assets/javascripts/translations/streama.translations.js
streama.translations.js

I'm not sure if It's worth it that I translated it :)

Korean Translation is here!

---

grails-app/assets/javascripts/translations/DE_de.js
grails-app/assets/javascripts/translations/streama.translations.js

@ManuGithubSteam added the german translation in PR #247. I reviewed his translation and fixed some typos and syntax.

Refined German translation from #247

---

README.md

So the day has finally come where I say good-bye to the old grails2 version of the app. May it rest in peace. I am thankful to the surge of contributions over the last weeks and all the great feedback to the new version! From here, its all uphill folks!

WIP: grails3 > Master

---

grails-app/assets/javascripts/streama/translations/DE_de.js
grails-app/assets/javascripts/streama/translations/EN_us.js
grails-app/assets/javascripts/streama/translations/ES_es.js
grails-app/assets/javascripts/streama/translations/FR_fr.js
grails-app/assets/javascripts/streama/translations/KR_ko.js
grails-app/assets/javascripts/streama/translations/NL_nl.js

In some translations, the language variables wasn't set. I also renamed the Korean translation file.

Added missing language variables in translations

---

README.md

Fix broken image link
**Note:** The episode browser image is broken for me.<br>GitHub says `Content length exceeded`.

Fix broken link inside README.md

---

grails-app/assets/stylesheets/_admin.scss
grails-app/assets/stylesheets/style.css
grails-app/services/streama/SettingsService.groovy

Added actual validation, so now there has to be entered a valid URL like http://localhost:8080.
Added URL testing, so now the validation will try to connect to the Base URL to make sure it is valid.
This should solve a bug pointed out in #177

Base URL validation rework #177

---

grails-app/services/streama/FileService.groovy

This should fix the issue with playing video on IOS. An error gets produced but it does play, I need to look into why this is happening.

Fixed issue with IOS not playing video

---

CustomRegex.yml
build.gradle
grails-app/assets/javascripts/streama/controllers/createFromFileCtrl.modal.js
grails-app/assets/javascripts/streama/templates/modal--create-from-file.tpl.htm
grails-app/controllers/streama/FileController.groovy
grails-app/init/streama/Application.groovy
grails-app/services/streama/TheMovieDbService.groovy

Added:
- Custom regexes can be added through yaml-file called CustomRegex.yml (Will be read on startup)
- Simple tree view for folders
- Selected files are parsed and metadata are returned by server
- Selected files are then added as movie or episode of a show and local files are added to their respective movie or episode

Finished basic functionality for bulk create.

---

.gitignore
grails-app/services/streama/VideoService.groovy
src/test/groovy/streama/VideoServiceSpec.groovy
src/test/groovy/streama/VideoSpec.groovy

- Added some new tests for Video domain.
- Added test for VideoService delete method.
- Added build folder generated by intellij in .gitignore.

Added some new tests

---

grails-app/assets/javascripts/streama/streama.translations.js
grails-app/assets/javascripts/streama/translations/DE_de.js
grails-app/assets/javascripts/streama/translations/DK_da.js
grails-app/assets/javascripts/streama/translations/EN_us.js
grails-app/assets/javascripts/streama/translations/ES_es.js
grails-app/assets/javascripts/streama/translations/FR_fr.js
grails-app/assets/javascripts/streama/translations/KR_ko.js
grails-app/assets/javascripts/streama/translations/NL_nl.js
grails-app/assets/javascripts/streama/translations/PT_br.js

Thought I would do some danish translations ;)

Danish Translations

---

grails-app/assets/javascripts/streama/translations/PT_br.js

added new strings and translation fix some words and the code format

add new strings and more

---

grails-app/assets/javascripts/streama/translations/IT_it.js

Fix a JS error in translation again.

Fix JS error in italian translation

---

grails-app/assets/javascripts/streama/streama.run.js
grails-app/conf/application.yml
grails-app/controllers/streama/LoginController.groovy
grails-app/controllers/streama/SettingsController.groovy
grails-app/controllers/streama/UserController.groovy
grails-app/services/streama/DefaultDataService.groovy
grails-app/services/streama/SettingsService.groovy
grails-app/views/index.gsp
grails-app/views/templates/_header_anonymous.gsp

I made a change in te application to enable access and reproduce videos without login.
The changes are:
- Added a setting to enable or disable the anonymous access. This settings control a user with "anonymous" username, to simulate the access without login (if check this setting and the user not exists or is disabled, the user is created or enabled. if disable the setting, the user is drop). This is because using Spring Security and the InterceptUrl, i can't add the anonymous access in that map (it can't be disable in execution easily)
- Added a special user called "anonymous" (commented in the previous point). In the user section in admin page, the changes in this user modify the "anonymous_access" setting. (if disable, delete or change the username, the setting is disabled, and if …

Issue #353: Enable anonymous access

---

grails-app/assets/javascripts/streama/controllers/modal-movie-ctrl.js
grails-app/assets/javascripts/streama/controllers/modal-tvshow-ctrl.js
grails-app/assets/javascripts/streama/templates/modal--movie.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--tvShow.tpl.htm
grails-app/controllers/streama/SettingsController.groovy
grails-app/controllers/streama/TheMovieDbController.groovy
grails-app/services/streama/DefaultDataService.groovy
grails-app/services/streama/SettingsService.groovy
grails-app/services/streama/TheMovieDbService.groovy

I read this issue #336 and I implemented for entire system as a request param in all requests to TMdb API. The Api language can be configured in Admin Settings page. 
If the language is not available for request movie/tv show, it responses like an empty language parameter (in english).

Added optional TheMovieDbApiLanguage setting

---

.dockerignore
.travis.yml
Dockerfile

Travis will build and push docker image when a git tag is pushed. No branch filtering.

Build and push docker image on tag

---

grails-app/assets/javascripts/streama/directives/streama-video-player-directive.js

wait this should be on master. :/ Reverts dularion/streama#458

Revert "Changed bindkey for fullscreen FROM "alt+enter" TO "f""

---

build.gradle
grails-app/assets/javascripts/streama/controllers/imageChooserModalCtrl.js
grails-app/assets/javascripts/streama/controllers/modal-movie-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/services/modal-service.js
grails-app/assets/javascripts/streama/templates/modal--image-chooser.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--movie.tpl.htm
grails-app/controllers/streama/TheMovieDbController.groovy
grails-app/services/streama/TheMovieDbService.groovy

feature: image chooser for movie-backdrop

---

grails-app/assets/javascripts/streama/streama.routes.js
grails-app/assets/javascripts/streama/translations/DE_de.js
grails-app/assets/javascripts/streama/translations/DK_da.js
grails-app/assets/javascripts/streama/translations/EN_us.js
grails-app/assets/javascripts/streama/translations/ES_es.js
grails-app/assets/javascripts/streama/translations/FR_fr.js
grails-app/assets/javascripts/streama/translations/IT_it.js
grails-app/assets/javascripts/streama/translations/JA_ja.js
grails-app/assets/javascripts/streama/translations/KR_ko.js
grails-app/assets/javascripts/streama/translations/NL_nl.js
grails-app/assets/javascripts/streama/translations/PT_br.js
grails-app/views/login/auth.gsp

Addresses https://github.com/dularion/streama/issues/484

session expired handling, based on #484

---

grails-app/assets/javascripts/streama/controllers/dash-ctrl.js
grails-app/assets/javascripts/streama/services/media-list-service.js
grails-app/assets/javascripts/streama/templates/profile.tpl.htm
grails-app/assets/javascripts/streama/translations/DE_de.js
grails-app/assets/javascripts/streama/translations/DK_da.js
grails-app/assets/javascripts/streama/translations/EN_us.js
grails-app/assets/javascripts/streama/translations/ES_es.js
grails-app/assets/javascripts/streama/translations/FR_fr.js
grails-app/assets/javascripts/streama/translations/IT_it.js
grails-app/assets/javascripts/streama/translations/JA_ja.js
grails-app/assets/javascripts/streama/translations/KR_ko.js
grails-app/assets/javascripts/streama/translations/NL_nl.js
grails-app/assets/javascripts/streama/translations/PT_br.js
grails-app/assets/stylesheets/_misc.scss
grails-app/controllers/streama/UserController.groovy
grails-app/domain/streama/User.groovy
grails-app/views/user/current.gson

adresses https://github.com/dularion/streama/issues/500

user setting for nr of entries, #500

---

grails-app/assets/javascripts/streama/controllers/settings-settings-ctrl.js

Fixes issue where settings would be validated twice.

Prevent settings being validated twice

---

grails-app/controllers/streama/TheMovieDbController.groovy
grails-app/services/streama/TheMovieDbService.groovy

fixed utf-8 encoding in TheMovieDbController and TheMovieDbService

---

grails-app/assets/stylesheets/_login.scss
grails-app/services/streama/DefaultDataService.groovy
grails-app/taglib/streama/AssetSettingTagLib.groovy
grails-app/views/login/auth.gsp

Add setting to change login background

---

index.html

previous links are taking to a blank page

Fixing the wiki links

---

build.gradle
grails-app/assets/javascripts/streama/controllers/settings-user-activity-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/streama.routes.js
grails-app/assets/javascripts/streama/templates/settings-settings.tpl.htm
grails-app/assets/javascripts/streama/templates/settings-user-activity.tpl.htm
grails-app/assets/javascripts/streama/templates/settings.tpl.htm
grails-app/assets/stylesheets/_util.scss
grails-app/conf/application.groovy
grails-app/controllers/streama/UserActivityController.groovy
grails-app/controllers/streama/UserController.groovy
grails-app/domain/streama/UserActivity.groovy
grails-app/services/streama/DefaultDataService.groovy
grails-app/services/streama/SettingsService.groovy
grails-app/services/streama/UserActivityService.groovy
grails-app/views/userActivity/_userActivity.gson
grails-app/views/userActivity/index.gson

This PR addresses the issue #212 
Here are some screenshots of the implementation:

Account sharing / User Activity (security measures) #212

---

grails-app/assets/javascripts/streama/templates/modal--create-from-file-recursive-item.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--video.tpl.htm
grails-app/controllers/streama/TheMovieDbController.groovy
grails-app/services/streama/BulkCreateService.groovy

This PR addresses https://github.com/dularion/streama/issues/480 https://github.com/dularion/streama/issues/498 and https://github.com/dularion/streama/issues/597
Warning! This is not a queue to fix the API-limit! this is simply a friendlier output of the existing error.

improve error for movie db limit bulk

---

grails-app/assets/stylesheets/_admin.scss
grails-app/assets/stylesheets/_btn.scss
grails-app/assets/stylesheets/_media-display.scss
grails-app/assets/stylesheets/_misc.scss
grails-app/assets/stylesheets/_player-controls.scss
grails-app/assets/stylesheets/_util.scss
grails-app/assets/stylesheets/_variables.scss

Fixed instances where SASS variables weren't used when setting colours.

SASS Variable Colour Enforcement

---

grails-app/assets/javascripts/streama/controllers/modal-movie-ctrl.js
grails-app/conf/application.groovy

fixed edit info doesn't save #614 and removed unnecessary movie save action(?)

fixed edit info doesn't save

---

grails-app/assets/javascripts/streama/controllers/settings-users-ctrl.js
grails-app/assets/javascripts/streama/templates/modal--create-user.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--edit-user.tpl.htm

Allow language selection in user manager

---

grails-app/assets/javascripts/streama/directives/streama-video-image.js
grails-app/assets/javascripts/streama/directives/streama-video-player-directive.js
grails-app/assets/javascripts/streama/services/media-list-service.js
grails-app/assets/javascripts/streama/services/player-service.js
grails-app/assets/javascripts/streama/templates/admin-movies.tpl.htm
grails-app/assets/javascripts/streama/templates/dash.tpl.htm
grails-app/assets/javascripts/streama/templates/directive--streama-video-image.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--movie.tpl.htm
grails-app/assets/javascripts/streama/templates/streama-video-player.tpl.htm
grails-app/assets/stylesheets/_player.scss
grails-app/domain/streama/Video.groovy
grails-app/services/streama/marshallers/PlayerMarshallerService.groovy
src/main/groovy/streama/traits/SimpleInstance.groovy

- fix scrubbing-flickering for player
- display autoplay for suggested videos - only enabled for episodes now

Feature: next video now as a small media-display (relates to #583)

---

build.gradle
grails-app/assets/javascripts/streama/controllers/settings-users-ctrl.js
grails-app/assets/javascripts/streama/services/player-service.js
grails-app/assets/javascripts/streama/templates/modal--edit-user.tpl.htm
grails-app/conf/application.yml
grails-app/services/streama/DefaultDataService.groovy
grails-app/services/streama/marshallers/MarshallerService.groovy
grails-app/views/user/current.gson

Updated drivers that allows streama to connect to mysql, added expiring user toggle in edit users tab so you dont have to delete them you can just expire them, and added a new role called 'trusted users' which allows you to control who can download the movie files if that is enabled.

Fix for connecting to new mysql version, added new stuff

---

grails-app/services/streama/DefaultDataService.groovy

This bug crash the startup of app, I sent an isolated PR for this, because the faster I correct the better

Remove invalid object passed as parameter roles in DefaultDataService

---

grails-app/services/streama/ViewingStatusService.groovy

Fixes #708
Not sure this is the most elegant solution, but it seems to work.

Fix viewing status for movies

---

grails-app/assets/javascripts/streama/translations/DE_de.js

improved german translation

---

grails-app/services/streama/VideoService.groovy

removed code that makes streama always play the episode with the highest season/episode number

---

grails-app/assets/javascripts/streama/translations/ES_es.js

It's my first PR, hope it's everything alright!

Improved ES_es.js spanish translation

---

grails-app/conf/application.yml

You forgot to adjust the drive class name for the mysql profile on 98134b54b3555f95901534ae89a35b4c16c6b168

Fix mysql driver class name on mysql profile

---

grails-app/assets/javascripts/streama/templates/modal--edit-user.tpl.htm
grails-app/assets/javascripts/streama/templates/settings-user-activity.tpl.htm
grails-app/domain/streama/Video.groovy

Fixed #775 | Edit users password in the admin panel
Fixes #849 | Admin panel view history s{episodenum}e{seasonnum} && Fixes movie title

Fix for 2 issues

---

grails-app/assets/javascripts/streama/controllers/dash-ctrl.js
grails-app/controllers/streama/UserController.groovy

fix initMedia method in dash-ctrl: currentUser.data always undefined, user`s data was in currentUser
fix amountOfMediaEntries parameter saving: add 'include' into bindData() in UserController

#901: User Setting Not Working: Amount of Videos on Dashboard

---

grails-app/assets/javascripts/streama/templates/dash.tpl.htm

fix tmpl for local images, displayed in "new releases" section

---

grails-app/views/templates/_header_anonymous.gsp

This PR addresses issue raised at https://github.com/streamaserver/streama/issues/919

Fix layout issue for anonymous users

---

build.gradle
grails-app/conf/application.yml
grails-app/conf/spring/resources.groovy
src/main/groovy/streama/LdapUserDetailsContextMapper.groovy

This adds basic LDAP support using the spring-security-ldap plugin. #226

Add LDAP support

---

grails-app/assets/javascripts/streama/templates/dash.tpl.htm

- Modified url to use original size (Resolution was lacking)
- Modified css to vertically center image

Changed new releases poster

---

grails-app/services/streama/BulkCreateService.groovy

The TV show bulk matcher system supports multiple regexes. This PR adds multiple regex support to the movie bulk matcher system.

Add support for multiple movie regexes

---

grails-app/assets/javascripts/streama/controllers/dash-ctrl.js
grails-app/assets/javascripts/streama/controllers/modal-media-detail-ctrl.js
grails-app/assets/javascripts/streama/services/api-service.js
grails-app/assets/javascripts/streama/templates/dash.tpl.htm
grails-app/assets/javascripts/streama/templates/modal--media-detail.tpl.htm
grails-app/assets/stylesheets/_dash.scss
grails-app/assets/stylesheets/_main.scss
grails-app/assets/stylesheets/_media-display.scss
grails-app/controllers/streama/DashController.groovy
grails-app/domain/streama/TvShow.groovy
grails-app/services/streama/MediaService.groovy
grails-app/services/streama/marshallers/MarshallerService.groovy

Adding a Shuffle / Random Episode Feature to the TV Shows. This currently only support shows and episodes from Official Seasons. Movies have not be addressed.

Random Episode Feature for TV Shows

---

grails-app/assets/javascripts/streama/streama.translations.js
grails-app/assets/javascripts/streama/translations/CAT_cat.js
grails-app/assets/javascripts/streama/translations/EN_us.js

Catalan is a language that is widely spoken in Spain.

Catalan translation added
